FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    git \
    curl \
    python3 \
    python3-pip \
    imagemagick \
    python3-pycryptodome \
    && rm -rf /var/lib/apt/lists

RUN pip3 install pycryptodome

